fix: tensorflow 2.3 cpu
ydataai/dockerfiles pull request #32
Opened 2020-12-01 17:00 UTC by victoriavilasb

2020-12-01 17:35 UTC, portellaa commented on data-science/jupyterlab-tensorflow-2/requirements.txt
> +tensorflow-cpu
missing version

2020-12-02 18:12 UTC, rafaelcpalmeida commented on data-science/jupyterlab-tensorflow-2/requirements.txt
> +tensorflow-cpu==2.3.1
Why locking on 2.3.1 and not having a wildcard on the patch version?

2020-12-04 16:47 UTC, rafaelcpalmeida commented
According to the [docs](https://www.tensorflow.org/install/gpu#older_versions_of_tensorflow), `tensorflow-gpu` and `tensorflow-cpu` separation is just for the 1.15 and lower versions. 🤔

2020-12-07 14:10 UTC, victoriavilasb commented on data-science/jupyterlab-tensorflow-2/requirements.txt
> +tensorflow-cpu
resolved

2021-01-11 18:04 UTC, portellaa commented
> According to the [docs](https://www.tensorflow.org/install/gpu#older_versions_of_tensorflow), `tensorflow-gpu` and `tensorflow-cpu` separation is just for the 1.15 and lower versions. 🤔

no, in this case it's correct. 
- for v1: tensorflow is cpu bounded, so if you want gpu you have to use tensorflow-gpu
- for v2: tensorflow is gpu bounded, so if you want cpu you have to use tensorflow-cpu

2021-01-11 19:03 UTC, portellaa requested changes
this will remove the gpu version. we need to have both

2021-01-11 19:04 UTC, portellaa commented
don't forget to link #64

2021-01-13 00:14 UTC, portellaa approved these changes

2021-01-13 00:18 UTC, merged