feat: Add GPU acceleration supported images
ydataai/dockerfiles pull request #36
Opened 2020-12-05 03:54 UTC by rafaelcpalmeida

2020-12-07 11:35 UTC, victoriavilasb commented on data-science/h2oflow-3.32.0.2/gpu/entrypoint.sh
> +exec "$@"
is this just a test?

2020-12-07 12:09 UTC, rafaelcpalmeida commented on data-science/h2oflow-3.32.0.2/gpu/entrypoint.sh
> +exec "$@"
The "teste" part yes, thank your noticing 🙇🏽

2020-12-09 11:04 UTC, portellaa requested changes
why is this a breaking change? the purpose is to add GPU support, not breaking things.

why did you remove nvidia-cuda image? don't know if you are aware, but that is the base image for synthesizers.

i don't think this Makefile solution is the best. we end up repeating a lot of files, Dockerfile and sometimes requirements.
I think you should have a specific makefile for each folder, i don't want to replicate changes across makefiles, unless they are completely different

2020-12-09 14:29 UTC, rafaelcpalmeida commented on data-science/h2oflow-3.32.0.2/cpu/Dockerfile
> +ENV UID 1000
Yes. Thank you 🙇🏽

2020-12-10 09:46 UTC, portellaa commented on data-science/h2oflow-3.32.0.2/gpu/Dockerfile
> +    libpython3.6-dev \
we are installing python using conda, as far as i know. this will make to have two python versions. and we are running python 3.7

2020-12-10 09:46 UTC, portellaa commented on data-science/h2oflow-3.32.0.2/gpu/Dockerfile
> +RUN chown ydata:${UID} /usr/local/bin/entrypoint.sh && chmod u+x /usr/local/bin/entrypoint.sh
don't see the need of this

2020-12-10 09:46 UTC, portellaa commented on data-science/jupyterlab-1.2.15_tensorflow-2.3/gpu/Dockerfile
> +RUN pip --no-cache-dir install -r /tmp/requirements.txt
why are we using conda for tensorflow 1.15 and pip for tensorflow 2.3?

2020-12-10 09:46 UTC, portellaa commented on nvidia-cuda.Dockerfile
> -ARG CUDA
this was required in the next steps, i was having issues after the `FROM` because CUDA wasn't set

2020-12-10 09:46 UTC, portellaa commented on nvidia-cuda.Dockerfile
> +ARG LIBCUBLAS
`LIBCUBLAS` doesn't needs to be injected, this has to be the version to be used and doesn't work properly if changed (that's why i didn't injected in the first place)

2020-12-10 09:46 UTC, portellaa commented on nvidia-cuda.Dockerfile
> +    libnvinfer-plugin${LIBNVINFER} && \
please remove `&&`

2020-12-14 19:24 UTC, portellaa commented on .github/workflows/prereleased.yaml
> +    branches: [ master ]
please revert this

2020-12-14 19:24 UTC, portellaa commented on data-science/h2oflow-3.32.0.2/gpu/build.args
> +TAG=gpu-cuda10.1-test
wrong value

2020-12-14 19:24 UTC, portellaa commented on data-science/h2oflow-3.32.0.2/gpu/Dockerfile
> +RUN chown ydata:${UID} /usr/local/bin/entrypoint.sh && chmod u+x /usr/local/bin/entrypoint.sh
what about this? and the size of this image?

2020-12-14 19:24 UTC, portellaa commented on data-science/h2oflow-3.32.0.2/gpu/Dockerfile
> +RUN echo ". $CONDA_DIR/etc/profile.d/conda.sh" >> ~/.profile
and this

2020-12-14 19:24 UTC, portellaa commented on data-science/h2oflow-3.32.0.2/cpu/build.args
> +TAG=cpu-test
wrong value

2020-12-14 19:24 UTC, portellaa commented on data-science/jupyterlab-1.2.15/gpu-cuda10.0/build.args
> +TAG=gpu-cuda10.0-test
wrong value

2020-12-14 19:24 UTC, portellaa commented on data-science/jupyterlab-1.2.15/gpu-cuda10.1/build.args
> +TAG=gpu-cuda10.1-test
wrong value

2020-12-14 19:24 UTC, portellaa commented on data-science/jupyterlab-1.2.15_pytorch-1.7/cpu/build.args
> +TAG=cpu-test
wrong value

2020-12-14 19:24 UTC, portellaa commented on data-science/jupyterlab-1.2.15_pytorch-1.7/gpu/build.args
> +TAG=gpu-cuda10.1-test
wrong value

2020-12-14 19:24 UTC, portellaa commented on data-science/jupyterlab-1.2.15_tensorflow-1.15/cpu/build.args
> +TAG=cpu-test
wrong value

2020-12-14 19:24 UTC, portellaa commented on data-science/jupyterlab-1.2.15_tensorflow-1.15/gpu/build.args
> +TAG=gpu-cuda10.0-test
wrong value

2020-12-14 19:24 UTC, portellaa commented on data-science/jupyterlab-1.2.15_tensorflow-2.3/cpu/build.args
> +TAG=cpu-test
wrong value

2020-12-14 19:24 UTC, portellaa commented on data-science/jupyterlab-1.2.15_tensorflow-2.3/gpu/build.args
> +TAG=gpu-cuda10.1-test
wrong value

2020-12-14 19:29 UTC, portellaa commented on data-science/h2oflow-3.32.0.2/gpu/build.args
> +TAG=1.0.0-gpu
and the cuda version?

2020-12-14 20:04 UTC, portellaa approved these changes

2020-12-14 22:51 UTC, merged