feat: Jupyter Lab with R and R bundles
ydataai/dockerfiles pull request #72
Opened 2021-01-07 00:19 UTC by victoriavilasb

Closes #65 
Closes #67

2021-01-12 14:22 UTC, rafaelcpalmeida approved these changes

2021-01-12 15:54 UTC, rafaelcpalmeida commented on images-builder.sh
> +    ;;
```suggestion
        for type in "${laboratories_images_types[@]}"
        do
            make build IMAGE="data-science/jupyterlab" TYPE="$type" TAG="$2"
            make push IMAGE="data-science/jupyterlab" TYPE="$type" TAG="$2"
        done
    ;;
```

2021-01-14 12:41 UTC, portellaa requested changes

2021-01-14 12:41 UTC, portellaa commented on data-science/jupyterlab/r/Dockerfile
> +RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager @techrah/text-shortcuts --dev-build=False --minimize=False
text-shortcuts?

2021-01-14 12:41 UTC, portellaa commented on data-science/jupyterlab/r/conda.txt
> +conda-forge::nodejs=13.13.0
can we use the version from pkg/main? 10.13
if not, let's use the lts

2021-01-14 12:41 UTC, portellaa commented on data-science/jupyterlab_r_tensorflow-2.3/Dockerfile
> +RUN Rscript -e "tensorflow::install_tensorflow(method = 'conda', envname = 'r-reticulate', version='2.3.0-${TYPE}')"
can we use 2.3 or 2.3.* or something like that in the version of the tensorflow? because the last one is 2.3.2

2021-01-14 12:41 UTC, portellaa commented on data-science/jupyterlab_r_tensorflow-2.3/cpu/requirements.txt
> +tensorflow-cpu==2.3.0rc2
tensorflow-cpu==2.3.* instead of that

2021-01-14 12:41 UTC, portellaa commented on data-science/jupyterlab_r_tensorflow-2.3/gpu/requirements.txt
> +tensorflow==2.3.*
tensorflow==2.3.*

2021-01-14 12:41 UTC, portellaa commented on data-science/jupyterlab_r_torch-1.7/Dockerfile
> +LABEL JupyterLabVersion=1.2.15
LABEL ai.ydata.laboratory.jupyterlab.version=2.2.9

2021-01-14 12:41 UTC, portellaa commented on data-science/jupyterlab_r_torch-1.7/Dockerfile.gpu
> +LABEL JupyterLabVersion=1.2.15
LABEL ai.ydata.laboratory.jupyterlab.version=2.2.9

2021-01-14 12:41 UTC, portellaa commented on images-builder.sh
> +        echo make push IMAGE="data-science/laboratories-base" TYPE="$type" TAG="$2"
why echo?

2021-01-14 12:47 UTC, victoriavilasb commented on images-builder.sh
> +    ;;
ok

2021-01-14 12:50 UTC, victoriavilasb commented on data-science/jupyterlab/r/Dockerfile
> +RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager @techrah/text-shortcuts --dev-build=False --minimize=False
its a recommended extension to use with r

2021-01-14 13:06 UTC, victoriavilasb commented on data-science/jupyterlab/r/conda.txt
> +conda-forge::nodejs=13.13.0
ok

2021-01-14 13:13 UTC, victoriavilasb commented on data-science/jupyterlab_r_tensorflow-2.3/Dockerfile
> +RUN Rscript -e "tensorflow::install_tensorflow(method = 'conda', envname = 'r-reticulate', version='2.3.0-${TYPE}')"
ok, it works

2021-01-14 13:13 UTC, victoriavilasb commented on data-science/jupyterlab_r_tensorflow-2.3/cpu/requirements.txt
> +tensorflow-cpu==2.3.0rc2
ok

2021-01-14 13:14 UTC, victoriavilasb commented on data-science/jupyterlab_r_tensorflow-2.3/gpu/requirements.txt
> +tensorflow==2.3.*
same thing?

2021-01-14 13:17 UTC, victoriavilasb commented on images-builder.sh
> +        echo make push IMAGE="data-science/laboratories-base" TYPE="$type" TAG="$2"
sorry, i forgot this. It was a test

2021-01-14 13:19 UTC, victoriavilasb commented on data-science/jupyterlab_r_torch-1.7/Dockerfile.gpu
> +LABEL JupyterLabVersion=1.2.15
ok

2021-01-14 13:19 UTC, victoriavilasb commented on data-science/jupyterlab_r_torch-1.7/Dockerfile
> +LABEL JupyterLabVersion=1.2.15
ok

2021-01-14 13:56 UTC, portellaa approved these changes

2021-01-14 21:30 UTC, merged